/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HealthCareEquipmentAdmin;

import Code.EnterPrise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 * Panel for managing administrative tasks in the context of a health care
 * equipment administrator's user interface. Allows the administrator to manage
 * organizations, employees, and user accounts within the enterprise. Also
 * displays the enterprise name and provides buttons to navigate to different
 * management panels.
 *
 * @author Milindh R Kashyap
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel uppercontainer;
    EnterPrise enter;

    /**
     * Creates new form AdminWorkAreaJPanel.
     *
     * @param uppercontainer The JPanel where this panel is placed.
     * @param enter The enterprise where the administrator belongs.
     */
    public AdminWorkAreaJPanel(JPanel uppercontainer, EnterPrise enter) {
        initComponents();
        this.uppercontainer = uppercontainer;
        this.enter = enter;
        jlbl2.setText(enter.getOrgName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        jlbl1 = new javax.swing.JLabel();
        jlbl2 = new javax.swing.JLabel();
        OrgManageBtn = new javax.swing.JButton();
        ManageEmployeeBtn = new javax.swing.JButton();
        ManageUserBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        Header.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("MY Work Area - Administrative Role");

        jlbl1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbl1.setText("Enterprise : ");

        jlbl2.setText("<Value>");

        OrgManageBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrgManageBtn.setText("Manage Organization");
        OrgManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrgManageBtnActionPerformed(evt);
            }
        });

        ManageEmployeeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageEmployeeBtn.setText("Manage Employee");
        ManageEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmployeeBtnActionPerformed(evt);
            }
        });

        ManageUserBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageUserBtn.setText("Manage User");
        ManageUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jlbl1)
                        .addGap(27, 27, 27)
                        .addComponent(jlbl2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrgManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl1)
                    .addComponent(jlbl2))
                .addGap(75, 75, 75)
                .addComponent(OrgManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManageEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ManageUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OrgManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrgManageBtnActionPerformed
        ManageOrganizationJPanel manageOrgJPanel = new ManageOrganizationJPanel(uppercontainer, enter.getOrgaDirectory());
        uppercontainer.add("manageOrgJPanel", manageOrgJPanel);
        CardLayout layout = (CardLayout) uppercontainer.getLayout();
        layout.next(uppercontainer);
    }//GEN-LAST:event_OrgManageBtnActionPerformed

    private void ManageEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmployeeBtnActionPerformed
        // TODO add your handling code here:
        ManageEmployeeJPanel manageemployeeJPanel = new ManageEmployeeJPanel(uppercontainer, enter.getOrgaDirectory());
        uppercontainer.add("manageemployeeJPanel", manageemployeeJPanel);
        CardLayout layout = (CardLayout) uppercontainer.getLayout();
        layout.next(uppercontainer);
    }//GEN-LAST:event_ManageEmployeeBtnActionPerformed

    private void ManageUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserBtnActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(uppercontainer, enter);
        uppercontainer.add("ManageUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) uppercontainer.getLayout();
        layout.next(uppercontainer);
    }//GEN-LAST:event_ManageUserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JButton ManageEmployeeBtn;
    private javax.swing.JButton ManageUserBtn;
    private javax.swing.JButton OrgManageBtn;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel jlbl2;
    // End of variables declaration//GEN-END:variables
}
