/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HospitalAdmin;

import Code.Organization.Directory_Organization;
import Code.Organization.Organization;
import Code.Organization.Organization.OrganizationType;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * JPanel class for managing hospital organizations. This class provides
 * functionality to view, add, and manage different types of organizations in a
 * hospital.
 *
 * @author Milindh R Kashyap
 */
public class HospitalOrganizationManageJPanel extends javax.swing.JPanel {

    private Directory_Organization od;
    private JPanel panel;

    /**
     * Creates new form ManagePanel_Organization. Initializes the panel with
     * organization data and combo boxes.
     *
     * @param p Parent panel for card layout.
     * @param od OrganizationDirectory containing hospital organizations.
     */
    public HospitalOrganizationManageJPanel(JPanel p, Directory_Organization od) {
        initComponents();
        this.panel = p;
        this.od = od;
        fillRows();
        fillCmb();
    }

    /**
     * Fills the table with existing organizations.
     */
    private void fillRows() {
        DefaultTableModel m = (DefaultTableModel) tblOrg.getModel();
        m.setRowCount(0);
        for (Organization o : od.getOrganizations()) {
            Object[] r = new Object[2];
            r[0] = o.getOrgId();
            r[1] = o.getOrgName();
            m.addRow(r);
        }
    }

    /**
     * Fills the organization type combo box with available organization types.
     */
    private void fillCmb() {
        cmbOrg.removeAllItems();
        for (OrganizationType t : Organization.OrganizationType.values()) {
            if (!OrganizationType.Admin.getValue().equals(t.getValue())) {
                cmbOrg.addItem(t);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblOrgType = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        cmbOrg = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        btnOrgAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Manage Organization");

        lblOrgType.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblOrgType.setText("Organization Type ");

        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(tblOrg);

        cmbOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrgActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnOrgAdd.setBackground(new java.awt.Color(153, 153, 153));
        btnOrgAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOrgAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddUser.jpg"))); // NOI18N
        btnOrgAdd.setText("Add Organization");
        btnOrgAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 231, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOrgType)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(232, 232, 232))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOrgAdd)
                                .addGap(278, 278, 278))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader)
                    .addComponent(btnBack))
                .addGap(78, 78, 78)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrgType))
                .addGap(30, 30, 30)
                .addComponent(btnOrgAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrgActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        panel.remove(this);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnOrgAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgAddActionPerformed
        OrganizationType ot = (OrganizationType) cmbOrg.getSelectedItem();
        od.addOrg(ot);
        fillRows();
    }//GEN-LAST:event_btnOrgAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOrgAdd;
    private javax.swing.JComboBox cmbOrg;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblOrgType;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblOrg;
    // End of variables declaration//GEN-END:variables
}
