/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Supplier;

import Code.Account;
import Code.EcoSystem;
import Code.Organization.Organization;
import Code.Organization.Organization_Supplier;
import Code.WorkQueue.SupplierWorkRequest;
import Code.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * JPanel class for the supplier work area, allowing suppliers to process and
 * manage work requests. Displays a table of work requests with details such as
 * medicine name, quantity, sender, receiver, status, and delivery time.
 * Suppliers can process, refresh, assign work requests to themselves, or go
 * back. Handles actions such as processing, refreshing, and assigning work
 * requests.
 *
 * @author Milindh R Kashyap
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    private Organization_Supplier os;
    private JPanel panel;
    private Account acc;
    private EcoSystem eco;

    /**
     * Creates new form WorkAreaPanel_Supplier
     */
    public SupplierWorkAreaJPanel(JPanel panel, EcoSystem eco, Account acc, Organization o) {
        initComponents();
        this.panel = panel;
        this.acc = acc;
        this.eco = eco;
        this.os = (Organization_Supplier) o;
        fillRows();
    }

    /**
     * Fills the table rows with work request details.
     */
    private void fillRows() {
        DefaultTableModel m = (DefaultTableModel) tblSup.getModel();
        m.setRowCount(0);

        for (WorkRequest wq : os.getWQ().getWorkRequestList()) {
            Object[] row = new Object[6];
            row[0] = ((SupplierWorkRequest) wq);
            row[1] = ((SupplierWorkRequest) wq).getQuantity();
            row[2] = wq.getSender().getEmp().getEName();
            row[3] = wq.getReceiver() != null ? wq.getReceiver().getEmp().getEName() : null;
            row[4] = wq.getStatus();
            row[5] = ((SupplierWorkRequest) wq).getDeliveryTime();
            m.addRow(row);
        }

        Object[] crocinData = {"Crocin", "VERY CRITICAL(<2 HRS)", "Milind", "Ravikiran", "Completed", "08-09-2019"};  // Third column is left empty for status
        Object[] insulinData1 = {"Insulin", "LOW PRIORITY(<24 HRS)", "Rakshith", "Ravikiran", "Assigned", "05-03-2019"};
        Object[] insulinData2 = {"Insulin", "MODERATE(<5 HRS)", "Pragnesh", "Ravikiran", "Pending", "12-17-2019"};
        Object[] ventolineData = {"Ventoline", "LOW PRIORITY(<24 HRS)", "Milind", "Ravikiran", "Completed", "06-11-2019"};
        Object[] paracetomolData = {"Paracetomol", "VERY CRITICAL(<2 HRS)", "Milind", "Ravikiran", "Completed", "08-23-2019"};
        Object[] tamifluData = {"Tamiflu (influenza)", "MODERATE(<5 HRS)", "Milind", "Ravikiran", "Pending", "04-30-2019"};

        // Add hardcoded data to the table model
        m.addRow(crocinData);
        m.addRow(insulinData1);
        m.addRow(insulinData2);
        m.addRow(ventolineData);
        m.addRow(paracetomolData);
        m.addRow(tamifluData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPro = new javax.swing.JButton();
        btnRef = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tblSup = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        btnPro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPro.setText("Process");
        btnPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProActionPerformed(evt);
            }
        });

        btnRef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRef.setText("Refresh");
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("SUPPLIER WORK AREA ");

        tblSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Quantity", "Sender", "Receiver", "Status", "Delivery Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(tblSup);

        btnAssign.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SupplierImage.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(208, 208, 208))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnAssign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRef, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(btnPro, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblHeader)))
                .addGap(16, 16, 16)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign)
                    .addComponent(btnRef))
                .addGap(18, 18, 18)
                .addComponent(btnPro)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProActionPerformed

        int clicked = tblSup.getSelectedRow();

        if (clicked < 0) {
            return;
        }

        SupplierWorkRequest sq = (SupplierWorkRequest) tblSup.getValueAt(clicked, 0);

        sq.setStatus("Processing");

        ViewSupplierRequestJPanel mp = new ViewSupplierRequestJPanel(panel, sq);
        panel.add("ManageWorkRequestPanel_Supplier", mp);
        CardLayout l = (CardLayout) panel.getLayout();
        l.next(panel);
    }//GEN-LAST:event_btnProActionPerformed

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed

        fillRows();
    }//GEN-LAST:event_btnRefActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed

        int clicked = tblSup.getSelectedRow();

        if (clicked < 0) {
            return;
        }

        WorkRequest wq = (WorkRequest) tblSup.getValueAt(clicked, 0);
        wq.setReceiver(acc);
        wq.setStatus("Assigned");
        fillRows();
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnPro;
    private javax.swing.JButton btnRef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblSup;
    // End of variables declaration//GEN-END:variables
}
