/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Code.EnterPrise;
import UI.HospitalAdmin.HospitalAccountManageJPanel;
import UI.HospitalAdmin.HospitalEmployeeManageJPanel;
import UI.HospitalAdmin.HospitalOrganizationManageJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 * JPanel class for the administrative work area in the hospital. 
 * This class provides options to manage organizations, employees, and user accounts within the enterprise.
 * 
 * @author Milindh R Kashyap
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel panel;
    EnterPrise enterprise;

    /**
     * Creates new form WorkAreaPanel_Admin.Initializes the panel with the parent panel and enterprise information.
     * 
     * @param p
     * @param e
     */
    public AdminWorkAreaJPanel(JPanel p, EnterPrise e) {
        initComponents();
        this.panel=p;
        this.enterprise=e;
        lblValue.setText(e.getOrgName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnOrg = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("My Work Area - Administrative Role");

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEnterprise.setText("Enterprise:");

        lblValue.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblValue.setText("<value>");

        btnOrg.setBackground(new java.awt.Color(153, 153, 153));
        btnOrg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnOrg.setText("Manage Organization");
        btnOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgActionPerformed(evt);
            }
        });

        btnEmp.setBackground(new java.awt.Color(153, 153, 153));
        btnEmp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEmp.setText("Manage Employee");
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });

        btnUser.setBackground(new java.awt.Color(153, 153, 153));
        btnUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnUser.setText("Manage User");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(453, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeader)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValue)
                    .addComponent(lblEnterprise))
                .addGap(81, 81, 81)
                .addComponent(btnOrg)
                .addGap(18, 18, 18)
                .addComponent(btnEmp)
                .addGap(18, 18, 18)
                .addComponent(btnUser)
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgActionPerformed
        HospitalOrganizationManageJPanel manageOrganizationPanel = new HospitalOrganizationManageJPanel(panel, enterprise.getOrgaDirectory());
        panel.add("manageOrganizationPanel", manageOrganizationPanel);
        CardLayout l = (CardLayout) panel.getLayout();
        l.next(panel);       // TODO add your handling code here:
    }//GEN-LAST:event_btnOrgActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        HospitalEmployeeManageJPanel manageEmployeePanel = new HospitalEmployeeManageJPanel(panel, enterprise.getOrgaDirectory());
        panel.add("manageEmployeePanel", manageEmployeePanel);
        CardLayout l = (CardLayout) panel.getLayout();
        l.next(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmpActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        HospitalAccountManageJPanel  manageAccountPanel = new HospitalAccountManageJPanel(panel, enterprise);
        panel.add("manageAccountPanel",manageAccountPanel);
        CardLayout l = (CardLayout) panel.getLayout();
        l.next(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnOrg;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
