/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Pharmacy;

import Code.Account;
import Code.DrugPantry;
import Code.DrugPantryList;
import Code.EnterPrise;
import Code.Network;
import Code.Organization.Organization;
import Code.Organization.Organization_Pharmacy;
import Code.WorkQueue.PharmacyWorkRequest;
import Code.WorkQueue.SupplierWorkRequest;
import Code.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * JPanel class for managing pharmacy medicine inventory and related work
 * requests. Provides functionalities such as adding medicines, viewing details,
 * checking inventory status, and handling work requests from doctors.
 *
 * @author Milindh R Kashyap
 */
public class PharmacyWorkAreaJPanel extends javax.swing.JPanel {

    private Network network;
    private Organization_Pharmacy op;
    private Organization orgz;
    private DrugPantryList dp;
    private EnterPrise enterprise;
    private Account acc;
    JPanel panel;

    /**
     * Creates new form PharmacyWorkAreaJPanel.
     *
     * @param panel The panel where this panel is added.
     * @param acc The account associated with this panel.
     * @param enterprise The enterprise associated with this panel.
     * @param op The pharmacy organization associated with this panel.
     * @param network The network associated with this panel.
     */
    public PharmacyWorkAreaJPanel(JPanel panel, Account acc, EnterPrise enterprise, Organization_Pharmacy op, Network network) {
        initComponents();
        this.op = (Organization_Pharmacy) op;
        this.panel = panel;
        this.network = network;
        this.enterprise = enterprise;
        this.dp = dp;
        this.acc = acc;
        arrangeRows();
        fillDocRows();
    }

    public void fillDocRows() {

        DefaultTableModel tab = (DefaultTableModel) tblDoc.getModel();
        tab.setRowCount(0);
        System.out.println("****" + op.getWQ().getWorkRequestList().size());
        System.out.println("****" + op.getOrgName());

        for (WorkRequest wr : op.getWQ().getWorkRequestList()) {
            Object[] o = new Object[4];
            String drug = ((PharmacyWorkRequest) wr).getMedicationName();
            System.out.println("****" + drug);
            o[0] = drug;
            int num = ((PharmacyWorkRequest) wr).getQuantity();
            o[1] = num;
            o[2] = ((PharmacyWorkRequest) wr).getStatus();
            tab.addRow(o);
        }
        

        // Hardcoded data
        Object[] crocinData = {"Crocin", 10, "Pending"};  // Third column is left empty for status
        Object[] insulinData1 = {"Insulin", 10000, "Assigned"};
        Object[] insulinData2 = {"Insulin", 900, "Pending"};
        Object[] ventolineData = {"Ventoline", 4, "Completed"};
        Object[] paracetomolData = {"Paracetomol", 66, "Completed"};
        Object[] tamifluData = {"Tamiflu (influenza)", 168, "Pending"};

        // Add hardcoded data to the table model
        tab.addRow(crocinData);
        tab.addRow(insulinData1);
        tab.addRow(insulinData2);
        tab.addRow(ventolineData);
        tab.addRow(paracetomolData);
        tab.addRow(tamifluData);
    }

    public void arrangeRows() {

        int rc = tblPharmacy.getRowCount();
        DefaultTableModel tbl = (DefaultTableModel) tblPharmacy.getModel();
        for (int i = rc - 1; i >= 0; i--) {
            tbl.removeRow(i);
        }
        for (DrugPantry i : op.getDrugs()) {
            Object o[] = new Object[6];
            o[0] = i;
            o[1] = i.getSerialNo();
            o[2] = i.getQuantitypresent();
            o[3] = i.getQuantityneeded();
            o[4] = i.getReorderQuantity();
            o[5] = i.getReorderStatus();
            tbl.addRow(o);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tblPharmacy = new javax.swing.JTable();
        btnStatus = new javax.swing.JButton();
        lblSerialNumber = new javax.swing.JLabel();
        lblMedicine = new javax.swing.JLabel();
        lblAvailableQuantity = new javax.swing.JLabel();
        lblReqQuantity = new javax.swing.JLabel();
        lblReorder = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        txtMedicine = new javax.swing.JTextField();
        txtAvailableQuantity = new javax.swing.JTextField();
        txtReqQuantity = new javax.swing.JTextField();
        txtReorder = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAddMedicine = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnReqs = new javax.swing.JButton();
        btnViewReq = new javax.swing.JButton();
        lblDocTbl = new javax.swing.JLabel();
        scrollPane2 = new javax.swing.JScrollPane();
        tblDoc = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("PHARMACY MEDICINE INVENTORY LOG");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1069, -1));

        tblPharmacy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICINE NAME", "SERIAL NUMBER", "AVAILABLE QUANTITY", "REQUIRED QUANTITY", "REORDER LEVEL", "REORDER STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(tblPharmacy);

        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1025, 80));

        btnStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnStatus.setText("INVENTORY STATUS CHECK!");
        btnStatus.setPreferredSize(null);
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 260, -1));

        lblSerialNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSerialNumber.setText("SERIAL NUMBER:");
        add(lblSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        lblMedicine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMedicine.setText("MEDICINE NAME:");
        add(lblMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 120, -1));

        lblAvailableQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAvailableQuantity.setText("AVAILABLE QUANTITY:");
        add(lblAvailableQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 160, -1));

        lblReqQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblReqQuantity.setText("REQUIRED QUANTITY:");
        add(lblReqQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 150, -1));

        lblReorder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblReorder.setText("REORDER LEVEL:");
        add(lblReorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, -1));
        add(txtSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 140, 20));
        add(txtMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 140, 20));
        add(txtAvailableQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 140, 20));
        add(txtReqQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 140, 20));
        add(txtReorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 140, 25));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnAddMedicine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddMedicine.setText("ADD MEDICINE");
        btnAddMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicineActionPerformed(evt);
            }
        });
        add(btnAddMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 257, -1));

        btnDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDetails.setText("VIEW DETAILS >>");
        btnDetails.setPreferredSize(null);
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 260, -1));

        btnReqs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReqs.setText("VIEW REQUESTS");
        btnReqs.setPreferredSize(null);
        btnReqs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqsActionPerformed(evt);
            }
        });
        add(btnReqs, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 260, -1));

        btnViewReq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewReq.setText("VIEW REQUESTS FROM DOCTORS");
        btnViewReq.setPreferredSize(null);
        btnViewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReqActionPerformed(evt);
            }
        });
        add(btnViewReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 260, -1));

        lblDocTbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDocTbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDocTbl.setText("View Requests from Doctor:");
        add(lblDocTbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 150, 1069, 35));

        tblDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICINE NAME", "QUANTITY", "STATUS"
            }
        ));
        scrollPane2.setViewportView(tblDoc);

        add(scrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 825, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        for (DrugPantry dp : op.getDrugs()) {

            if (dp.getQuantitypresent() <= dp.getReorderQuantity()) {
                if (!dp.getReorderStatus().equals("Y")) {
                    SupplierWorkRequest swr = new SupplierWorkRequest();

                    dp.setReorderStatus("Y");
                    swr.setMedicationName(dp.getDrugName());
                    swr.setQuantity(dp.getQuantityneeded());
                    swr.setSender(acc);

                    acc.getWorkQueue().getWorkRequestList().add(swr);
                    for (EnterPrise enterprise : network.getDirectoEnterpri().getEnterpList()) {
                        System.out.println("***** Organization Name:" + enterprise.getOrgName());
                        for (Organization g : enterprise.getOrgaDirectory().getOrganizations()) {
                            System.out.println("***** Organization Name:" + g.getOrgName());
                            if (g.getOrgName().equals("Supplier Organization")) {
                                System.out.println("True");

                                System.out.println("***** organization Name" + g.getOrgName());

                                g.getWQ().getWorkRequestList().add(swr);
                            }
                        }

                    }

                }

            }
        }
        JOptionPane.showMessageDialog(null, "Status of inventory checked and updated!", "Warning", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        panel.remove(this);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicineActionPerformed
        DrugPantry dp = new DrugPantry();

        String pre = txtAvailableQuantity.getText();
        try {
            Integer.parseInt(pre);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please provide valid data in Available Quantity");
            return;
        }
        dp.setDrugName(txtMedicine.getText());
        int qp = Integer.parseInt(txtAvailableQuantity.getText());
        dp.setQuantitypresent(qp);
        String sno = txtSerialNumber.getText();
        try {
            Integer.parseInt(sno);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Serial Number must be integer!");
            return;
        }
        int sn = Integer.parseInt(txtSerialNumber.getText());
        dp.setSerialNo(sn);
        String rc = txtReqQuantity.getText();
        try {
            Integer.parseInt(rc);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Required quantity must be integer!");
            return;
        }
        int rt = Integer.parseInt(txtReqQuantity.getText());
        dp.setQuantityneeded(rt);

        String ro = txtReorder.getText();
        try {
            Integer.parseInt(ro);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Reorder level must be integer!");
            return;
        }
        int rl = Integer.parseInt(txtReorder.getText());
        dp.setReorderQuantity(rl);
        op.addDrug(dp);
        dp.setReorderStatus("N");

        DefaultTableModel dtm = (DefaultTableModel) tblPharmacy.getModel();

        dtm.setRowCount(0);
        for (DrugPantry drp : op.getDrugs()) {
            Object row[] = new Object[5];
            row[0] = drp;
            row[1] = drp.getSerialNo();
            row[2] = drp.getQuantitypresent();
            row[3] = drp.getQuantityneeded();
            row[4] = drp.getReorderQuantity();
            dtm.addRow(row);
        }

        JOptionPane.showMessageDialog(null, "Medicine Added Successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMedicineActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int val = tblPharmacy.getSelectedRow();
        if (val < 0) {
            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DrugPantry dp = (DrugPantry) tblPharmacy.getValueAt(val, 0);

        CardLayout c = (CardLayout) panel.getLayout();
        panel.add("UpdateEntryJPanel", new UpdateDetailsJPanel(panel, acc, enterprise, dp));
        c.next(panel);
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnReqsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqsActionPerformed
        CardLayout c = (CardLayout) panel.getLayout();
        panel.add("ViewrequestJPanel", new ViewMedicinesRequestJPanel(panel, acc, enterprise, orgz));
        c.next(panel);
    }//GEN-LAST:event_btnReqsActionPerformed

    private void btnViewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReqActionPerformed
//        fillDocRows();
        fillDocRows();
    }//GEN-LAST:event_btnViewReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicine;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnReqs;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnViewReq;
    private javax.swing.JLabel lblAvailableQuantity;
    private javax.swing.JLabel lblDocTbl;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblReorder;
    private javax.swing.JLabel lblReqQuantity;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTable tblDoc;
    private javax.swing.JTable tblPharmacy;
    private javax.swing.JTextField txtAvailableQuantity;
    private javax.swing.JTextField txtMedicine;
    private javax.swing.JTextField txtReorder;
    private javax.swing.JTextField txtReqQuantity;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
